# Generated by Django 2.0 on 2019-09-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xfzauth', '0003_auto_20190906_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='uid',
        ),
    ]
